version: 0.2 
phases:
  install:
    runtime-versions:
      java : corretto11
  pre_build:
    commands:
      - echo "pre-build started"
      - pwd
      - ls -lrta
      - cd $CODEBUILD_SRC_DIR
   #   - pwd
   #   - ls -lrta
  build:
    commands:
      - echo Build started on `date`
      - mvn clean validate compile test install verify package
      - ls -lrta
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/devops-1.0.5-SNAPSHOT.war
     - '**/*'
